### ISSUE TITLE
when running inference.py, "Unresolved object in checkpoint"

### ISSUE THREAD

**Issue by yana-xuyan** [bckim92/sequential-knowledge-transformer#1]
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested [Op:RestoreV2]
WARNING:tensorflow:Unresolved object in checkpoint: (root).save_counter
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).save_counter
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.deliberation_decoder
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.deliberation_decoder
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.deliberation_decoder.decoder_stack
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.deliberation_decoder.decoder_stack
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.deliberation_decoder._copy_q_layer
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.deliberation_decoder._copy_q_layer
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.deliberation_decoder._copy_k_layer
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.deliberation_decoder._copy_k_layer
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.deliberation_decoder._copy_v_layer
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.deliberation_decoder._copy_v_layer
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.deliberation_decoder._copy_layer
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.deliberation_decoder._copy_layer
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.deliberation_decoder.decoder_stack.layers
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.deliberation_decoder.decoder_stack.layers
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.encoder.layer_with_weights-0.encoder.layers.1.attention_layer.value_dense.bias
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.encoder.layer_with_weights-0.encoder.layers.1.attention_layer.value_dense.bias
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.encoder.layer_with_weights-0.encoder.layers.2.attention_layer.query_dense.kernel
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.encoder.layer_with_weights-0.encoder.layers.2.attention_layer.query_dense.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.encoder.layer_with_weights-0.encoder.layers.2.attention_layer.query_dense.bias
[WARNING:2020-01-17 23:56:54] Unresolved object in checkpoint: (root).model.encoder.layer_with_weights-0.encoder.layers.2.attention_layer.query_dense.bias
...
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
[WARNING:2020-01-17 23:56:54] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.

**Comment by bckim92** [comment]
Hi, thank you for your interest in our work.

Released checkpoints are trained using our ICLR submission version code, which is slightly different from the current released version. We cleaned many unsued parts from our submission version, and that warning is one of the traces.

Fortunately, it would not affect the results; thus, you can just ignore the warnings. Thank you :)
