### ISSUE TITLE
 data bias as the first knowledge is always the golden knowledge.

### ISSUE THREAD

**Issue by youngornever** [bckim92/sequential-knowledge-transformer#5]
hi, I notice that the first knowledge is always the golden knowledge when we get the knowledge loss and selection accuracy.
There is a risk that model learns to select the first knowledge and get the 100% selection accuracy.

**Comment by bckim92** [comment]
Hi, thanks for your interest in our work. As you mentioned, if we correlate each knowledge candidates, there could be a risk to achieve 100% selection accuracy. However, in our implementation, we don't correlate with each other; thus, our model cannot know the relative position of each knowledge candidate (i.e., cannot take advantage of positional bias). This implementation follows the original implementation of ParlAI, and I had the same concern as yours when I first saw the code.

Thanks!
Byeongchang
